In [1]:
import numpy as np
from numpy import genfromtxt
from itertools import combinations
import torch
from torch import nn
import torch.nn.functional as F
import torch.optim as optim
import matplotlib.pyplot as plt

In [2]:
data = genfromtxt('small_file.txt', delimiter=',')
data[:,4] =(data[:,4]-np.min(data[:,4]))/(np.max(data[:,4])-np.min(data[:,4]))
print(data)

[[ 0.          1.128016    2.699852   -2.22828     0.27121927]
 [ 1.          0.952915    0.878809    0.519144    0.95261156]
 [ 1.          0.434082    2.311936   -2.573923    0.93668561]
 [ 2.          2.209619    2.334585    1.107064    0.52416023]
 [ 3.          1.71197     1.119164    1.189179    0.78435412]
 [ 3.          0.461599    0.144536   -2.364426    0.75403444]
 [ 4.          2.029792    1.303054    1.287916    0.        ]
 [ 5.          0.756178    2.309371   -1.809833    0.68407621]
 [ 6.          2.1872      2.85122     0.476108    0.8842718 ]
 [ 7.          1.921325    2.40708    -1.854133    1.        ]
 [ 7.          0.24677     1.512456    0.972258    0.95922116]
 [ 8.          2.12424     0.532672    1.190137    0.63181968]
 [ 9.          2.165567    1.332818    0.780826    0.52338727]
 [10.          1.927867    1.392146   -2.161047    0.83159162]
 [10.          0.155214    2.217043   -2.08358     0.81032574]
 [11.          2.17151     0.050683   -2.559912    0.75

### reshape data

In [3]:
#print(np.min(data,axis=0)[0])
ll = []
true_vals = []
for i in range(int(np.min(data,axis=0)[0]),int(np.max(data,axis=0)[0]),3):
    mask = ((data[:,0] == i) | (data[:,0] == i+1) | (data[:,0] == i+2))
    evt = data[mask]
    #print(evt)
    #print(evt.shape[0])
    pair_indices = list(combinations(range(evt.shape[0]), 2))
    #print(pair_indices)
    for i, (idx1, idx2) in enumerate(pair_indices):
        l = []
        l.append(np.concatenate((evt[idx1,1:],evt[idx2,1:])))
        ll.append(l)
        if (evt[idx1,0] == evt[idx2,0]):
            true_vals.append(1)
        else:
            true_vals.append(0)
print(ll)
input_data = torch.FloatTensor(ll)
input_data = torch.squeeze(input_data)
input_data.shape
truth_class = torch.FloatTensor(true_vals)
print(truth_class.shape)

[[array([ 1.128016  ,  2.699852  , -2.22828   ,  0.27121927,  0.952915  ,
        0.878809  ,  0.519144  ,  0.95261156])], [array([ 1.128016  ,  2.699852  , -2.22828   ,  0.27121927,  0.434082  ,
        2.311936  , -2.573923  ,  0.93668561])], [array([ 1.128016  ,  2.699852  , -2.22828   ,  0.27121927,  2.209619  ,
        2.334585  ,  1.107064  ,  0.52416023])], [array([ 0.952915  ,  0.878809  ,  0.519144  ,  0.95261156,  0.434082  ,
        2.311936  , -2.573923  ,  0.93668561])], [array([0.952915  , 0.878809  , 0.519144  , 0.95261156, 2.209619  ,
       2.334585  , 1.107064  , 0.52416023])], [array([ 0.434082  ,  2.311936  , -2.573923  ,  0.93668561,  2.209619  ,
        2.334585  ,  1.107064  ,  0.52416023])], [array([ 1.71197   ,  1.119164  ,  1.189179  ,  0.78435412,  0.461599  ,
        0.144536  , -2.364426  ,  0.75403444])], [array([1.71197   , 1.119164  , 1.189179  , 0.78435412, 2.029792  ,
       1.303054  , 1.287916  , 0.        ])], [array([ 1.71197   ,  1.119164  ,  1.18

/home/tobiasjenegger/jupy/jup_notebook/lib/python3.6/site-packages/ipykernel_launcher.py:20: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ../torch/csrc/utils/tensor_new.cpp:201.)


### simple model

In [4]:
class feed_forward_model(nn.Module):
        def __init__(self):
                super().__init__()
                self.linear = torch.nn.Linear(8,10000)
                self.another_linear = torch.nn.Linear(10000,10000)
                self.activation = torch.nn.ReLU()
                self.linear_back = torch.nn.Linear(10000,1)

        def forward(self, x):
                output_tensor = self.linear(x)
                output_tensor = self.another_linear(output_tensor)
                output_tensor = self.activation(output_tensor)
                output_tensor = self.linear_back(output_tensor)
                output_tensor = torch.sigmoid(output_tensor)
                output_tensor = torch.squeeze(output_tensor)
                return output_tensor


## final training

In [5]:
print(input_data.shape)
n_epochs = 1000
model = feed_forward_model()
loss_fn = nn.BCELoss()  # binary cross entropy
optimizer = optim.SGD(model.parameters(), lr=9e-4)
model.train()
loss_val = []
for epoch in range(n_epochs):
    y_pred = model(input_data)
    y_true = truth_class
    loss = loss_fn(y_pred,y_true)
    loss_val.append(loss.detach().item())
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    print(f'Finished epoch {epoch}, latest loss {loss}')

torch.Size([60, 8])
Finished epoch 0, latest loss 0.7302961945533752
Finished epoch 1, latest loss 0.5685167908668518
Finished epoch 2, latest loss 0.49943655729293823
Finished epoch 3, latest loss 0.4650794565677643
Finished epoch 4, latest loss 0.44518986344337463
Finished epoch 5, latest loss 0.4320952296257019
Finished epoch 6, latest loss 0.4225238859653473
Finished epoch 7, latest loss 0.41493740677833557
Finished epoch 8, latest loss 0.4085501730442047
Finished epoch 9, latest loss 0.4029350280761719
Finished epoch 10, latest loss 0.3978523313999176
Finished epoch 11, latest loss 0.3931613862514496
Finished epoch 12, latest loss 0.38877829909324646
Finished epoch 13, latest loss 0.3846440017223358
Finished epoch 14, latest loss 0.3807210624217987
Finished epoch 15, latest loss 0.3769826292991638
Finished epoch 16, latest loss 0.37341099977493286
Finished epoch 17, latest loss 0.369988352060318
Finished epoch 18, latest loss 0.36670148372650146
Finished epoch 19, latest loss 0.36

Finished epoch 161, latest loss 0.21654874086380005
Finished epoch 162, latest loss 0.21606820821762085
Finished epoch 163, latest loss 0.2155899703502655
Finished epoch 164, latest loss 0.21511395275592804
Finished epoch 165, latest loss 0.21464137732982635
Finished epoch 166, latest loss 0.214170902967453
Finished epoch 167, latest loss 0.21370308101177216
Finished epoch 168, latest loss 0.21323730051517487
Finished epoch 169, latest loss 0.2127743661403656
Finished epoch 170, latest loss 0.21231451630592346
Finished epoch 171, latest loss 0.211856871843338
Finished epoch 172, latest loss 0.2114017903804779
Finished epoch 173, latest loss 0.2109489142894745
Finished epoch 174, latest loss 0.21049846708774567
Finished epoch 175, latest loss 0.2100500762462616
Finished epoch 176, latest loss 0.2096041738986969
Finished epoch 177, latest loss 0.2091599404811859
Finished epoch 178, latest loss 0.2087181657552719
Finished epoch 179, latest loss 0.2082790732383728
Finished epoch 180, lates

KeyboardInterrupt: 

In [ ]:
plt.plot(loss_val)
plt.xlabel("epochs")
plt.ylabel("loss value")